export const pilotResources = [
  {
    id: 'seed-food-franklin',
    name: 'Franklin Food Bank',
    category: 'Food Resources',
    address: '224 Churchill Ave, Somerset, NJ 08873',
    city: 'Somerset',
    state: 'NJ',
    zip: '08873',
    latitude: 40.5005,
    longitude: -74.4932,
    phone: '732-246-0009',
    website: 'https://franklinfoodbank.org',
    hours_text: 'Mon-Fri 9:00 AM-4:00 PM',
    hours_json: { mon: { open: '09:00', close: '16:00' }, tue: { open: '09:00', close: '16:00' }, wed: { open: '09:00', close: '16:00' }, thu: { open: '09:00', close: '16:00' }, fri: { open: '09:00', close: '16:00' } },
    rating: 4.8,
    transportation_available: true,
    free_service: true,
    notes: 'Food pantry, case referrals, and emergency household support.',
  },
  {
    id: 'seed-housing-somerset',
    name: 'Somerset County Board of Social Services',
    category: 'Shelters',
    address: '73 E High St, Somerville, NJ 08876',
    city: 'Somerville',
    state: 'NJ',
    zip: '08876',
    latitude: 40.5681,
    longitude: -74.6107,
    phone: '908-526-8800',
    website: 'https://www.co.somerset.nj.us',
    hours_text: 'Mon-Fri 8:30 AM-4:30 PM',
    hours_json: { mon: { open: '08:30', close: '16:30' }, tue: { open: '08:30', close: '16:30' }, wed: { open: '08:30', close: '16:30' }, thu: { open: '08:30', close: '16:30' }, fri: { open: '08:30', close: '16:30' } },
    rating: 4.4,
    transportation_available: true,
    free_service: true,
    notes: 'Housing, benefits, emergency assistance, and case management.',
  },
  {
    id: 'seed-recovery-middlesex',
    name: 'Rutgers UBHC Recovery Support',
    category: 'Recovery Programs',
    address: '671 Hoes Ln W, Piscataway, NJ 08854',
    city: 'Piscataway',
    state: 'NJ',
    zip: '08854',
    latitude: 40.5242,
    longitude: -74.4641,
    phone: '800-969-5300',
    website: 'https://ubhc.rutgers.edu',
    hours_text: '24/7 phone support',
    hours_json: { sun: { open: '00:00', close: '23:59' }, mon: { open: '00:00', close: '23:59' }, tue: { open: '00:00', close: '23:59' }, wed: { open: '00:00', close: '23:59' }, thu: { open: '00:00', close: '23:59' }, fri: { open: '00:00', close: '23:59' }, sat: { open: '00:00', close: '23:59' } },
    accepts_medicaid: true,
    rating: 4.6,
    transportation_available: false,
    free_service: true,
    notes: 'Behavioral health and recovery support navigation.',
  },
  {
    id: 'seed-jobs-goodwill',
    name: 'Goodwill NYNJ Career Center',
    category: 'Jobs / Staffing Agencies',
    address: '191 US-22, Green Brook Township, NJ 08812',
    city: 'Green Brook',
    state: 'NJ',
    zip: '08812',
    latitude: 40.5922,
    longitude: -74.4854,
    phone: '732-968-5050',
    website: 'https://www.goodwillnynj.org',
    hours_text: 'Mon-Sat 10:00 AM-7:00 PM',
    hours_json: { mon: { open: '10:00', close: '19:00' }, tue: { open: '10:00', close: '19:00' }, wed: { open: '10:00', close: '19:00' }, thu: { open: '10:00', close: '19:00' }, fri: { open: '10:00', close: '19:00' }, sat: { open: '10:00', close: '19:00' } },
    rating: 4.5,
    transportation_available: true,
    free_service: true,
    notes: 'Workforce readiness, retail employment, and reentry-friendly job support.',
  },
  {
    id: 'seed-veterans-va',
    name: 'VA New Jersey Health Care Access',
    category: 'Veteran Services',
    address: '385 Tremont Ave, East Orange, NJ 07018',
    city: 'East Orange',
    state: 'NJ',
    zip: '07018',
    latitude: 40.7555,
    longitude: -74.2343,
    phone: '973-676-1000',
    website: 'https://www.va.gov/new-jersey-health-care',
    hours_text: 'Mon-Fri 8:00 AM-4:30 PM',
    hours_json: { mon: { open: '08:00', close: '16:30' }, tue: { open: '08:00', close: '16:30' }, wed: { open: '08:00', close: '16:30' }, thu: { open: '08:00', close: '16:30' }, fri: { open: '08:00', close: '16:30' } },
    veteran_support: true,
    accepts_medicaid: true,
    rating: 4.3,
    transportation_available: true,
    free_service: true,
    notes: 'Veteran health care, benefits navigation, mental health, and transition support.',
  },
  {
    id: 'seed-legal-lsnj',
    name: 'Legal Services of Northwest Jersey',
    category: 'Legal Help',
    address: '90 Maple Ave, Somerville, NJ 08876',
    city: 'Somerville',
    state: 'NJ',
    zip: '08876',
    latitude: 40.5697,
    longitude: -74.6131,
    phone: '908-231-0840',
    website: 'https://www.lsnj.org',
    hours_text: 'Mon-Fri 9:00 AM-5:00 PM',
    hours_json: { mon: { open: '09:00', close: '17:00' }, tue: { open: '09:00', close: '17:00' }, wed: { open: '09:00', close: '17:00' }, thu: { open: '09:00', close: '17:00' }, fri: { open: '09:00', close: '17:00' } },
    rating: 4.4,
    transportation_available: false,
    free_service: true,
    notes: 'Civil legal help, benefits issues, housing stability, and reentry legal guidance.',
  },
  {
    id: 'seed-transport-njtransit',
    name: 'NJ TRANSIT Access Link',
    category: 'Transportation',
    address: '1 Penn Plaza East, Newark, NJ 07105',
    city: 'Newark',
    state: 'NJ',
    zip: '07105',
    latitude: 40.7346,
    longitude: -74.1642,
    phone: '973-491-4224',
    website: 'https://www.njtransit.com/accessibility/access-link-ada-paratransit',
    hours_text: 'Daily 8:30 AM-5:00 PM',
    hours_json: { sun: { open: '08:30', close: '17:00' }, mon: { open: '08:30', close: '17:00' }, tue: { open: '08:30', close: '17:00' }, wed: { open: '08:30', close: '17:00' }, thu: { open: '08:30', close: '17:00' }, fri: { open: '08:30', close: '17:00' }, sat: { open: '08:30', close: '17:00' } },
    rating: 4.1,
    transportation_available: true,
    free_service: false,
    notes: 'Transportation planning for eligible riders and appointment access.',
  },
  {
    id: 'seed-church-salvation',
    name: 'The Salvation Army New Brunswick',
    category: 'Community Outreach',
    address: '287 Handy St, New Brunswick, NJ 08901',
    city: 'New Brunswick',
    state: 'NJ',
    zip: '08901',
    latitude: 40.4864,
    longitude: -74.4518,
    phone: '732-545-1477',
    website: 'https://easternusa.salvationarmy.org/new-jersey/new-brunswick',
    hours_text: 'Mon-Fri 9:00 AM-4:00 PM',
    hours_json: { mon: { open: '09:00', close: '16:00' }, tue: { open: '09:00', close: '16:00' }, wed: { open: '09:00', close: '16:00' }, thu: { open: '09:00', close: '16:00' }, fri: { open: '09:00', close: '16:00' } },
    rating: 4.5,
    transportation_available: true,
    free_service: true,
    notes: 'Emergency assistance, food, spiritual support, and community referrals.',
  },
];

export const pilotVideos = [
  {
    id: 'seed-video-reset',
    title: 'Three Minutes to Reset Before a Craving Wins',
    description: 'A short grounding video for the moment between impulse and action.',
    media_type: 'video',
    category: 'Recovery',
    source_name: 'ReZilient Care Team',
    source_url: 'https://www.youtube.com/results?search_query=grounding+exercise+craving+recovery',
    youtube_video_id: 'search-grounding-craving',
    thumbnail_url: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80',
    channel_name: 'ReZilient Care Team',
    duration_seconds: 180,
    tags: ['Help', 'Recovery', 'Craving', 'Calm'],
    tone: 'motivational',
    recovery_stage: 'early_recovery',
    moderation_status: 'approved',
    is_featured: true,
    is_positive_content: true,
    helpful_count: 27,
  },
  {
    id: 'seed-video-reentry',
    title: 'Coming Home: First Week Reentry Structure',
    description: 'Practical steps for housing, phone calls, meetings, and the first job-search rhythm.',
    media_type: 'video',
    category: 'Reentry',
    source_name: 'ReZilient Field Guide',
    source_url: 'https://www.youtube.com/results?search_query=reentry+first+week+after+incarceration+support',
    youtube_video_id: 'search-reentry-first-week',
    thumbnail_url: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=800&q=80',
    channel_name: 'ReZilient Field Guide',
    duration_seconds: 420,
    tags: ['Reentry', 'Structure', 'Employment', 'Hope'],
    tone: 'educational',
    recovery_stage: 'reentry',
    moderation_status: 'approved',
    is_featured: true,
    is_positive_content: true,
    helpful_count: 18,
  },
];

export const pilotReadings = [
  {
    id: 'seed-reading-first-day',
    title: 'The First Day Does Not Need to Be Perfect',
    summary: 'A five-minute reminder that structure beats pressure when life is being rebuilt.',
    body: 'Start with food, a safe place, one support contact, and one honest check-in. Progress begins when today has a shape.',
    source_name: 'ReZilient',
    source_url: 'https://rezilient.app',
    author: 'ReZilient Care Team',
    category: 'Hope',
    tags: ['Help', 'Hope', 'Early Recovery'],
    reading_time_minutes: 5,
    tone: 'motivational',
    recovery_stage: 'early_recovery',
    moderation_status: 'approved',
    is_featured: true,
    is_positive_content: true,
    helpful_count: 34,
  },
  {
    id: 'seed-reading-support',
    title: 'How to Ask for Support Without Feeling Like a Burden',
    summary: 'A script-based guide for texting a sponsor, family member, mentor, or counselor.',
    body: 'Try: "I am having a hard hour, not a hard life. Can you check in with me for five minutes?" Clear asks make support easier to give.',
    source_name: 'ReZilient',
    source_url: 'https://rezilient.app',
    author: 'ReZilient Care Team',
    category: 'Healing',
    tags: ['Support Circle', 'Family', 'Sponsor'],
    reading_time_minutes: 4,
    tone: 'positive',
    recovery_stage: 'general',
    moderation_status: 'approved',
    is_featured: false,
    is_positive_content: true,
    helpful_count: 22,
  },
];

export const pilotAhHaMoments = [
  {
    id: 'seed-ahha-keys',
    title: 'The key was answering the first call',
    story: 'I kept waiting to feel ready. My Ah Ha Moment was realizing ready came after I answered my counselor and showed up to the meeting.',
    category: 'Hope',
    tags: ['accountability', 'meetings', 'support'],
    recovery_stage: 'early_recovery',
    moderation_status: 'approved',
    privacy: 'anonymous',
    is_positive_content: true,
    helpful_count: 19,
  },
  {
    id: 'seed-ahha-work',
    title: 'A resume was more than paper',
    story: 'When my mentor helped me write my resume, I saw my life as skills instead of mistakes. That changed how I walked into the interview.',
    category: 'Healing',
    tags: ['employment', 'mentor', 'reentry'],
    recovery_stage: 'reentry',
    moderation_status: 'approved',
    privacy: 'first_name_only',
    is_positive_content: true,
    helpful_count: 14,
  },
  {
    id: 'seed-ahha-veteran',
    title: 'I did not have to transition alone',
    story: 'The VA appointment, peer group, and gym schedule finally belonged on one calendar. My Ah Ha Moment was seeing support as structure.',
    category: 'Help',
    tags: ['veteran', 'calendar', 'structure'],
    recovery_stage: 'general',
    moderation_status: 'approved',
    privacy: 'anonymous',
    is_positive_content: true,
    helpful_count: 11,
  },
];

export const pilotMissionItems = [
  { title: 'Stay connected to support', why: 'Call or text one trusted person before isolation gets loud.', progress: 72 },
  { title: 'Make every required appointment', why: 'Structure protects freedom, health, and momentum.', progress: 64 },
  { title: 'Protect recovery time daily', why: 'Meetings, check-ins, and calm resets keep the day anchored.', progress: 80 },
  { title: 'Build work and housing stability', why: 'A comeback needs income, safety, and a plan.', progress: 46 },
  { title: 'Give back when strong enough', why: 'Helping someone else turns survival into leadership.', progress: 38 },
];

export const pilotItinerary = [
  { title: 'Morning check-in', time: '8:00 AM', route: '/DailyCheckIn', detail: 'Mood, craving intensity, support contact, and one note.' },
  { title: 'Job search block', time: '10:00 AM', route: '/ResourceHub', detail: 'Review staffing agencies and saved employment resources.' },
  { title: 'NA / peer meeting', time: '7:00 PM', route: '/JourneyRoadmap', detail: 'Meeting attendance plus transportation reminder.' },
];
