import { Briefcase, Building2, FileText, Gavel, HeartHandshake, Home, Scale, ShieldCheck, Users, Vote } from "lucide-react";

export const justiceTopics = [
  "Drug-related charges",
  "Probation/parole",
  "Veterans issues",
  "Housing",
  "Employment barriers",
  "Sentencing reform",
  "Expungement",
  "Family law",
  "Juvenile history",
  "Voting rights",
];

export const justiceArticles = [
  {
    id: "drug-sentencing-reform",
    category: "Sentencing reform",
    state: "Federal / State watch",
    title: "New sentencing reform legislation may affect older drug sentencing structures.",
    summary: "Several reform efforts are focused on reducing penalties tied to outdated drug sentencing rules and expanding review pathways.",
    changed: "More lawmakers are reviewing mandatory minimums, retroactive relief, and sentence review options for older drug cases.",
    affected: "People with drug-related convictions, families with loved ones still incarcerated, and reentry advocates.",
    future: "This could create more opportunities to ask about sentence review, clemency, or reentry support programs.",
    lawyerQuestions: ["Could this apply retroactively?", "Is there a filing deadline?", "What documents should my family gather?"],
    resources: ["Legal aid organizations", "Public defender reentry units", "Sentencing reform nonprofits"],
    icon: Scale,
    tone: "gold",
  },
  {
    id: "probation-parole-modernization",
    category: "Probation/parole",
    state: "State-by-state update",
    title: "Probation and parole changes are expanding incentives for stability and compliance.",
    summary: "Some states are reducing technical violation penalties and adding earned compliance credits for people meeting supervision goals.",
    changed: "Policy conversations are shifting toward support, incentives, and fewer returns to custody for non-criminal violations.",
    affected: "People on supervision, families, mentors, and case managers supporting reentry plans.",
    future: "Users may want to ask whether good-time credits, early termination, or violation alternatives are available.",
    lawyerQuestions: ["Can earned compliance reduce supervision time?", "What counts as a technical violation?", "Can missed appointments be repaired?"],
    resources: ["Probation office policy guide", "Reentry legal clinics", "Community supervision advocates"],
    icon: ShieldCheck,
    tone: "teal",
  },
  {
    id: "housing-rights-reentry",
    category: "Housing rights",
    state: "Local laws vary",
    title: "Second-chance housing policies are gaining attention in more cities and states.",
    summary: "Housing rights advocates are challenging blanket bans and encouraging individualized review for applicants with records.",
    changed: "Some jurisdictions are limiting how criminal history can be used in rental screening decisions.",
    affected: "People searching for housing after incarceration, families offering support, and housing navigators.",
    future: "Applicants may have more rights to request review, explain rehabilitation, or challenge unfair denials.",
    lawyerQuestions: ["Can a landlord deny me based only on record history?", "Do I have appeal rights?", "What proof of rehabilitation helps?"],
    resources: ["Fair housing groups", "Tenant rights clinics", "Reentry housing programs"],
    icon: Home,
    tone: "green",
  },
  {
    id: "employment-fair-chance",
    category: "Employment barriers",
    state: "National trend",
    title: "Fair-chance hiring laws continue to shape employment access for people with records.",
    summary: "More employers and states are adopting policies that delay background checks and require individualized assessments.",
    changed: "Hiring rules increasingly focus on relevance, time passed, rehabilitation, and job-related risk rather than automatic exclusion.",
    affected: "Job seekers with records, workforce programs, employers, and reentry coaches.",
    future: "Users may have better chances when prepared with references, training records, and a clear work-readiness plan.",
    lawyerQuestions: ["When can an employer ask about my record?", "Can I appeal a denial?", "Does expungement change what appears?"],
    resources: ["Workforce boards", "Fair-chance hiring groups", "Legal aid employment units"],
    icon: Briefcase,
    tone: "purple",
  },
  {
    id: "voting-rights-restoration",
    category: "Voting rights",
    state: "State-by-state update",
    title: "Voting rights restoration rules are changing across states.",
    summary: "Eligibility often depends on state law, sentence status, probation/parole status, and court financial obligations.",
    changed: "Some states have simplified restoration while others still require specific steps before registering.",
    affected: "People returning home, civic groups, families, and community organizers.",
    future: "Users should confirm current eligibility before registering and ask about restoration steps if unsure.",
    lawyerQuestions: ["Am I eligible while on supervision?", "Do fines or fees affect eligibility?", "Where can I verify safely?"],
    resources: ["Election protection groups", "Secretary of State offices", "Voting rights nonprofits"],
    icon: Vote,
    tone: "teal",
  },
  {
    id: "veteran-legislation",
    category: "Veterans issues",
    state: "Federal / State watch",
    title: "Veteran-specific reentry and treatment legislation is expanding support options.",
    summary: "New initiatives often focus on veterans courts, mental health diversion, housing, benefits access, and trauma-informed support.",
    changed: "Policy attention is increasing around veterans with justice involvement and co-occurring behavioral health needs.",
    affected: "Veterans, families, VA-linked providers, peer mentors, and reentry specialists.",
    future: "This may expand diversion, benefits navigation, and specialized treatment pathways.",
    lawyerQuestions: ["Is veterans court available?", "Can service history affect sentencing or diversion?", "Which VA records should I gather?"],
    resources: ["VA justice outreach", "Veterans legal clinics", "Veteran service organizations"],
    icon: HeartHandshake,
    tone: "gold",
  },
];

export const radarCategories = [
  { label: "Sentencing reform", icon: Gavel },
  { label: "Drug law changes", icon: Scale },
  { label: "Expungement", icon: FileText },
  { label: "Housing rights", icon: Building2 },
  { label: "Veterans legislation", icon: Users },
];